spring.application.name=salonflow
spring.datasource.url=jdbc:postgresql://localhost:5432/salonflow
spring.datasource.username=postgres
spring.datasource.password=SalonFlow2026!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true